#!/bin/sh

# Set these paths appropriately

BIN="/home/rizstwn/demo-skripsi/treetagger/bin"
CMD="/home/rizstwn/demo-skripsi/treetagger/cmd"
LIB="/home/rizstwn/demo-skripsi/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
