#!/bin/sh

# Set these paths appropriately

BIN="/home/rizstwn/demo-skripsi/treetagger/bin"
CMD="/home/rizstwn/demo-skripsi/treetagger/cmd"
LIB="/home/rizstwn/demo-skripsi/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

